### PR TITLE
Bash -> Clojure: Take 2

### PR DESCRIPTION
**Pull request by lispyclouds**

### CODE REVIEW

**Comment by lispyclouds** [comment]
Merge checklist:

- [ ] add the circle ci master only filter back
- [ ] add the same check as the shell script

**Comment by lispyclouds** [comment]
tagging @cap10morgan have a look, some tiny bits slipped the cracks in the last one, making sure second time's the charm 🙏🏽

**Review by cap10morgan — APPROVED** [review]
LGTM! Yay bb!

**Comment by borkdude** [comment]
@lispyclouds @cap10morgan Let's check in 15 minutes if the SNAPSHOT images are OK on Docker hub (and if the "latest" remain untouched).

**Pull request merged**
