### PR TITLE
Update build options for graal 23

### PR DESCRIPTION
**Pull request by jlesquembre**
If you decide to update to graal23, the `ReportAnalysisForbiddenType` option needs to be updated

`InHeap` and `Allocated` are now `Instantiated`, see https://github.com/oracle/graal/commit/b9d387c4251dd0cdb4eaf945f71357d14ff38398

Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/babashka/babashka/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [ ] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [ ] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by borkdude** [comment]
Thanks

**Comment by borkdude** [comment]
If you want to make a PR to upgrade to graalvm 23, also welcome. Note that I don't use a "latest" tag since this causes surprises in CI when suddently a newer point release is used, so I use the "archive" links.

**Comment by jlesquembre** [comment]
ok, let's try to upgrade to graalvm 23

**Comment by borkdude** [comment]
I'll take a look at this soon.

One thing that stood out:

```
ERROR in (into-array-fallback-test) (test_utils.clj:100)
expected: (= :f (bb nil "(first (first (into-array [(into-array [:f])])))"))
  actual: clojure.lang.ExceptionInfo: ----- Error --------------------------------------------------------------------
Type:     org.graalvm.nativeimage.MissingReflectionRegistrationError
Message:  The program tried to reflectively instantiate the array class

   clojure.lang.Keyword[]

without it being registered for runtime reflection. Add clojure.lang.Keyword[] to the reflection metadata to solve this problem. Note: Add "unsafeAllocated" to the array class registration to enable runtime instantiation. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help.
Location: <expr>:1:28
```

Perhaps something changed wrt/ reflection in 23?

**Comment by borkdude** [comment]
Upgraded to GraalVM 23 on master

**Comment by jlesquembre** [comment]
Nice!
What was the issue? this: https://github.com/babashka/babashka/pull/1745/commits/0fc5f12e3244e15fb6a520943fdee1686568bf81 ?

**Comment by borkdude** [comment]
Among other things, the whole PR reflects what was necessary

**Pull request closed without merging**
