### PR TITLE
Spire requires proxy support for java.io.PipedInputStream and java.io.PipedOutputStream

### PR DESCRIPTION
**Pull request by retrogradeorbit**
Please answer the following questions and leave the below in as part of your PR.

- [X] I have read the [developer documentation](https://github.com/babashka/babashka/blob/master/doc/dev.md).

- [X] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [X] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [X] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by retrogradeorbit** [comment]
working on test and changelog now...

**Comment by retrogradeorbit** [comment]
@borkdude are you happy with `java.utils.Scanner` being reflected? That code in spire can be rewritten.

**Comment by borkdude** [comment]
I'm merging this to a branch first to see what the change to binary size is. If that's ok, then I'll continue to merge to master.

**Comment by borkdude** [comment]
Almost all of the binary size was coming from Scanner, so I merged the proxy support but maybe you could explain how you're using Scanner and what the alternative would be?

**Comment by borkdude** [comment]
Decided to add `java.util.Scanner` anyway, agreed that it can be pretty useful, probably worth the 100kb.

**Comment by retrogradeorbit** [comment]
The Scanner code I'm using is just a clojure porting of some java code around processing the scp line protocol. It's actually quite simple so could be rewritten pretty easily:

https://github.com/epiccastle/spire/blob/f1161ae5ff74124d603c1679507fc0a1b31c26eb/src/clj/spire/pod/scp.clj#L375-L383

It is useful because it processes out of a reader. But if you want to trim it I'm ok with that.

**Comment by borkdude** [comment]
Eventually some library will use Scanner and I'll have to add it anyway, for 100kb I think it's not much of a problem.

**Pull request merged**
