### PR TITLE
Add ITransientSet and flatland.ordered-set

### LINKED ISSUE #1692: Feature request: Expose flatland.ordered.set/ordered-set
Follow-up to #447, could we get support for `flatland.ordered.set`?

```
$ rlwrap bb
[babashka] WARNING: task(s) 'run' override built-in command(s). Use :override-builtin true to disable warning.
Babashka v1.3.189 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require '[flatland.ordered.map :as om])
nil
user=> (require '[flatland.ordered.set :as os])
java.lang.Exception: Unable to resolve classname: clojure.lang.ITransientSet [at flatland/ordered/set.clj:4:3]
```

### PR DESCRIPTION
**Pull request by NoahTheDuke**
Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/babashka/babashka/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.

Closes #1692.

I am not able to run the tests locally (I get NPEs in `babashka.main/fn`), so my apologies if this is broken. I don't know enough about Babashka to solve the tests issue.

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
(Sorry for the force push, it won't happen again, just wanted to fix the temp commit message before you reviewed.)

**Comment by borkdude** [comment]
This PR seems to conflate a few things:

- Exposing stuff like described in the issue
- Changes to the pod tests, not sure what it has to do with the issue
- Exposing ITransientSet, not sure what it has to do with the issue

You may also want to bump this dependency to the newest release including the hashCode fix you made, which requires a new mvn release.

**Comment by NoahTheDuke** [comment]
I can bump the version, sure.

> Exposing ITransientSet, not sure what it has to do with the issue

Babashka can't use `ordered-set` as Babashka doesn't expose `ITransientSet`, which is used in ordered-set. I think that the most minimal change would be to include `ITransientSet` in Babashka and not expose ordered-set, but including it helps everyone.

https://github.com/clj-commons/ordered/blob/574e47018623b9f1b09b0f9b754b02d6633f3437/src/flatland/ordered/set.clj#L122-L143

> Changes to the pod tests, not sure what it has to do with the issue

I copied the changes from your original PR #447 where you changed the pod tests. I can remove those changes if they're not appropriate.

**Comment by borkdude** [comment]
> Babashka can't use ordered-set as Babashka doesn't expose ITransientSet, which is used in ordered-set. I think that the most minimal change would be to include ITransientSet in Babashka and not expose ordered-set, but including it helps everyone.

This isn't true as exposing a built-in dependency doesn't require running the source of that library through the interpreter.
I'll accept it though it's not strictly necessary, as it probably will help someone else in some point in the future.

> I can remove those changes if they're not appropriate.

Not necessary to make any changes on those.

**Comment by NoahTheDuke** [comment]
> This isn't true as exposing a built-in dependency doesn't require running the source of that library through the interpreter.

When I try to use `org.flatland/ordered-set` with babashka right now, it says it can't find `ITransientSet`. Is that not actually the bug here?

**Comment by borkdude** [comment]
The crux is in "right now". When you require it "right now" when adding that dep to bb.edn, it will run the library from source. But after this PR, it won't.

**Comment by NoahTheDuke** [comment]
Oh I see, that makes sense.

**Comment by borkdude** [comment]
Tests are failing with:

```
ERROR in (ordered-test) (test_utils.clj:82)
expected: (= (ordered-set :a 1 :b 2) (bb nil "(flatland.ordered.map/ordered-set :a 1 :b 2)"))
  actual: clojure.lang.ExceptionInfo: ----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Could not resolve symbol: flatland.ordered.map/ordered-set
Data:     {:type :sci/error, :line 1, :column 1, :file "<expr>", :phase "analysis"}
Location: <expr>:1:1
Phase:    analysis
```

Btw, you can run tests locally as well with `lein do clean, test :only ...`

**Comment by NoahTheDuke** [comment]
I've released org.flatland.ordered 1.15.12, but it looks like Ordered Sets also use `resolve`: https://github.com/clj-commons/ordered/blob/574e47018623b9f1b09b0f9b754b02d6633f3437/src/flatland/ordered/set.clj#L15

Will this be a problem with including them in Babashka?

**Comment by borkdude** [comment]
> Will this be a problem with including them in Babashka?

Yes, why wouldn't it be this time?

**Comment by borkdude** [comment]
Here's the fix I made for the ordered-map: https://github.com/clj-commons/ordered/commit/dd4bfd028556e5717f8d793050597f8e217ec5ea
The fix for ordered-set would be similar

**Comment by NoahTheDuke** [comment]
> Yes, why wouldn't it be this time?

I'm double checking that you're aware before you merge. I can fix that in ordered before updating here.

**Comment by borkdude** [comment]
Yeah, this PR won't get merged with that change as this will blow up the binary size of bb and its compilation time during the builds.

**Comment by NoahTheDuke** [comment]
Let me know what you think: https://github.com/clj-commons/ordered/pull/76

**Comment by borkdude** [comment]
See comments, tl;dr: this looks good, I'll merge tomorrow

**Comment by borkdude** [comment]
Thanks a lot. You can test this with:

``` clojure
bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --dev-build --dir /tmp
```

once the CI build finishes

**Comment by NoahTheDuke** [comment]
It works great, thank you.

**Pull request merged**
