### PR TITLE
Bumping selmer version to 1.12.59

### PR DESCRIPTION
**Pull request by didibus**
Please answer the following questions and leave the below in as part of your PR.

- [X] I have read the [developer documentation](https://github.com/babashka/babashka/blob/master/doc/dev.md).

- [ ] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

No, but we discussed it on the slack, I'm simply bumping Selmer version so it has access to the new resolve-arg fn from selmer.parser.

- [ ] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

No, not sure we need one just for a version bump?

- [ ] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.

Wasn't sure where to add it, in the Unreleased section?

### CODE REVIEW

**Comment by borkdude** [comment]
I think you also need to update the selmer configuration to expose the new function

**Comment by didibus** [comment]
I wasn't sure how to test it, because when doing `clj -M:babashka/dev` and form the REPL I was able to use it without any other change. Does that not reflect proper use?

**Comment by borkdude** [comment]
Can you give an example snippet of the selmer usage?

**Comment by didibus** [comment]
```
babashka on  master [?] via ☕ v17.0.5
x clj -M:babashka/dev
Babashka v1.3.182-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (require '[selmer.parser :as s])
nil
user=> (s/resolve-arg "{{hello}}" {:hello 123})
"123"
user=>
```

**Comment by borkdude** [comment]
Ah yes, it makes sense, everything is copied:

https://github.com/babashka/babashka/blob/af0937f0601ba94e53cbc966b777d5384ee8a3d1/feature-selmer/babashka/impl/selmer.clj#L34

**Comment by borkdude** [comment]
We also have Selmer's unit tests copied into babashka's repo. Perhaps it's worth updating those with your new tests.

**Comment by borkdude** [comment]
https://github.com/babashka/babashka/tree/master/test-resources/lib_tests/selmer

**Comment by didibus** [comment]
```
babashka on  master [!?] via ☕ v17.0.5 took 1m10s
> ./script/run_lib_tests
[...]
Ran 26 tests containing 93 assertions.
0 failures, 0 errors.
{:test 2298, :pass 14443, :fail 0, :error 0}
```

**Comment by borkdude** [comment]
Thanks!

Once the master build is finished, you can install the dev-build binary with:

```
bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --dev-build --dir /tmp
```

**Comment by didibus** [comment]
FYI, tried it with my script, and now I can run my script in bb and clj !

**Pull request merged**
