### PR TITLE
[#1521] Push images to GHCR

### PR DESCRIPTION
**Pull request by lispyclouds**
Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/babashka/babashka/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [ ] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by lispyclouds** [comment]
I have added those env var in circle using a classic token i generated with packages permissions. couldnt figure out the permissions for pacakges on the new tokens. the user is `lispyclouds` for now.

**Comment by borkdude** [comment]
@lispyclouds I think we can keep publishing to dockerhub until they shut things off. ghcr would be an additional thing people can move to over time.

**Comment by lispyclouds** [comment]
okay, will just do it as an extra tag and push

**Comment by borkdude** [comment]
LGTM. Shall we test this before merge to master, by removing the master only check temporarily?

**Comment by lispyclouds** [comment]
doing the build twice due to:
- the build and push are complected due to the multiarch buildx things
- its easier to simply remove the dockerhub code when moving than having complicated branched code

**Comment by lispyclouds** [comment]
merging to master should be safe enough, this is an accretive change for me.

**Comment by lispyclouds** [comment]
should be good now

**Comment by borkdude** [comment]
"this is an accretive change": I see enough points that could go wrong even with a small change.

does logging in twice undo the first login, or can you do multiple logins at the same time?

**Comment by borkdude** [comment]
and the thing I wanted to test mostly is if the github containers are really pushed: how is that evident? I've had credential-related failures enough that it warrants testing on this branch before going to master.

**Comment by lispyclouds** [comment]
makes sense. taking off the PR and the master check for the test.

> does logging in twice undo the first login, or can you do multiple logins at the same time?

multiple logins can exist as long as their URLs are different, which is the case here.

**Comment by borkdude** [comment]
And now? :)

**Comment by lispyclouds** [comment]
well want expecting this to pass in the first go but more from _can debug on master with less code changes_ 😛

**Comment by borkdude** [comment]
yeah right ;)

**Pull request merged**
