### PR TITLE
refactor: propose changing to working example found at

### PR DESCRIPTION
**Pull request by samrose**
https://github.com/Sohalt/write-babashka-application-example/commit/e24cd9e085aa7432bdda6cd4b55bdd3af8ef3f48

Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/babashka/babashka/blob/master/doc/dev.md).

- [ ] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by samrose** [comment]
I did not create a corresponding issue, but can if desired.

**Comment by borkdude** [comment]
@Sohalt I'll let you be the reviewer of this PR, if you don't mind

**Comment by samrose** [comment]
Oh, the comment got chopped but it should read that this updated example came directly from https://github.com/Sohalt/write-babashka-application-example/blob/main/flake.nix

**Comment by Sohalt** [comment]
Hi, thanks for updating the example here. Unfortunately the example at https://github.com/Sohalt/write-babashka-application-example/blob/main/flake.nix was a bit outdated as well 😅. I've archived that repo and directly added an example to https://github.com/Sohalt/write-babashka-application. I would suggest to simply link there from the babashka docs, since it's not really tied to babashka but specific to using [write-babashka-application](https://github.com/Sohalt/write-babashka-application).

**Comment by borkdude** [comment]
Ah yes, just a link will do :)

**Comment by samrose** [comment]
@Sohalt ok, I have revised it to just link to the example.

**Pull request merged**
