### PR TITLE
Convert more library tests

### PR DESCRIPTION
**Pull request by cldwalker**
Hi. This PR is a follow up to #1114 which moves more libraries to bb-tested-libs.edn using `add-libtest.clj`. I converted about 20 libraries and also addressed #1069 and #1064. The `add-libtest.clj` script has been improved with clojars data which removes the need to specify git urls most of the time e.g. `script/add-libtest.clj version-clj/version-clj -t`. Test counts on a mac for `master` and this branch are respectively `{:test 1120, :pass 6293, :fail 0, :error 0}` and `{:test 1300, :pass 8040, :fail 0, :error 0}`.

---
Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/babashka/babashka/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/babashka/babashka/blob/master/doc/dev.md#tests) to prevent against future regressions

- [-] I have updated the [CHANGELOG.md](https://github.com/babashka/babashka/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by borkdude** [comment]
I added `equals` from `java.util.Arrays` to master, this should fix 1 error. The other error is due to a `.contains` call on a LazySeq. Let's just change the test since this is atypical Clojure, I would say.

**Comment by borkdude** [comment]
@cldwalker I'm confused as to which PR I should have merged or merged first. Is this still relevant?

**Comment by cldwalker** [comment]
This is no longer relevant as this was a subset of #1120. I was trying to stage the PRs so you could review them in parts but I didn't point #1120 correctly. Looks like #1064 is done.
Let me know if you're ever concerned about too many library tests. It's gotten a lot easier to add them so I don't know when CI taking too long will be a concern

**Comment by borkdude** [comment]
@cldwalker Good points. I think currently it's ok. We could randomize the lib tests as well and then time-box them or so in the future or only run them in the linux build.

**Comment by borkdude** [comment]
@cldwalker Are there any open issues about lib tests that could be closed?

**Comment by cldwalker** [comment]
> @cldwalker Are there any open issues about lib tests that could be closed?

Just #1064

**Pull request closed without merging**
