### PR TITLE
make the REPL requires available to command-line scripts (closes #729)

### LINKED ISSUE #729: Add REPL requires to user namespace for one-liners
Map the REPL requires `(pprint, etc,)` also to the user namespace, so you can just write `(pprint *input*)`.

### PR DESCRIPTION
**Pull request by bobisageek**
I assume this is what you had in mind for #729

### CODE REVIEW

**Comment by bobisageek** [comment]
It looks like musl got updated in the last day or so (failing build uses 1.2.2-4, last build on master used 1.2.2-1)... I spent some time trying to figure out what changes are needed, but I'm not having a lot of luck. Given the nature of these changes, I'm imagining that the musl build (with the new version) will probably fail on master as well.

I'll see if I have any more luck with musl after I get some sleep, but it's sort of a blind spot for me, so I'm very open to suggestions. 😄

**Comment by borkdude** [comment]
@bobisageek Hm yeah, same problem with clj-kondo: https://github.com/clj-kondo/clj-kondo/issues/1365

**Comment by lispyclouds** [comment]
Maybe its something to do with the recent Debian 11 release. I will have a look today.

**Comment by thiagokokada** [comment]
Probably now that Debian 11 is released, unstable started to finally do big changes.

My suggestion is either to backport musl from Debian 11 release (should be the correct version), or better yet, just migrate to Debian 11 instead of using Debian 9: https://github.com/babashka/babashka/issues/866.

**Comment by thiagokokada** [comment]
> Probably now that Debian 11 is released, unstable started to finally do big changes.
> 
> My suggestion is either to backport musl from Debian 11 release (should be the correct version), or better yet, just migrate to Debian 11 instead of using Debian 9: #866.

Sadly, Clojure's docker image is still being compiled with Buster: https://hub.docker.com/_/clojure/

**Comment by bobisageek** [comment]
pulled in the changes from master - I was able to do a musl build with those changes on debian in WSL, so I think this should work now

**Comment by borkdude** [comment]
Thanks!

**Pull request merged**
