### PR TITLE
Allow building x86_64 or arm64 Docker images

### PR DESCRIPTION
**Pull request by cap10morgan**
Please answer the following questions and leave the below in as part of your PR.

- [X] I have read the [developer documentation](https://github.com/babashka/babashka/blob/master/doc/dev.md).

- [x] This PR correponds to an [issue with a clear problem statement](https://github.com/babashka/babashka/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).
Issue:
https://github.com/babashka/babashka/issues/1096

This will now default to building an image for the platform your Docker daemon is running on, but you can override it with the `--platform` arg to `docker buildx build`.

`TARGETARCH` build arg is documented here: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope.

Note that the multi-platform support requires using the [BuildKit backend in Docker](https://github.com/docker/buildx) which should be the default in recent versions of Docker.

### CODE REVIEW

**Comment by lispyclouds** [comment]
Thanks a lot for this @cap10morgan 😄 this is something is really wanted to have in the build process! @borkdude if you want I can follow through with this and help in the review.

**Comment by borkdude** [comment]
@lispyclouds @cap10morgan Cool! Can you also make an issue with some context about this change?

**Comment by cap10morgan** [comment]
Closes #1069

**Comment by borkdude** [comment]
Wrong issue number?

**Comment by cap10morgan** [comment]
> Wrong issue number?

Haha, yep. Thanks, fixed!

**Comment by cap10morgan** [comment]
Running some final tests now but I think this is ready for review

**Comment by cap10morgan** [comment]
CircleCI is [having some issues](https://status.circleci.com) right now

**Comment by lispyclouds** [comment]
Looks cool to me till now! How are we planning to push the image(s)? Using buildx or different tags? With buildx i think we need to update the docker version we are using on Circle too?

**Comment by cap10morgan** [comment]
> Looks cool to me till now! How are we planning to push the image(s)? Using buildx or different tags? With buildx i think we need to update the docker version we are using on Circle too?

I opened a separate issue for that: #1097 (links to my fork where I'm working on it)

**Comment by lispyclouds** [comment]
Looks okay to me, I can merge this once CircleCI is a bit better and if @borkdude has nothing to add.

**Review by lispyclouds — APPROVED** [review]

**Comment by borkdude** [comment]
Let's merge once CI confirms this is working correctly.

**Pull request merged**
