### PR TITLE
run lib tests in Windows CI

### PR DESCRIPTION
**Pull request by bobisageek**
From my local testing, it seems like the environment setup should be ok, but we'll see what Appveyor makes of it. :)

The change in the selmer test is due to what feels like a very esoteric issue with the URL paths for resources - I figure the testing is nicer to have, and then I'll look deeper into the issue once the tests are setup.

### CODE REVIEW

**Comment by borkdude** [comment]
@bobisageek It looks like most of them are passing :) Except for the \r\n thing, so we probably need a normalize-like feature in those lib tests.

**Comment by bobisageek** [comment]
Yeah - there is a 'fix line separator' function in there, but I'm guessing that the git checkout isn't using the system-dependent line separator, because the 'expected' has the windows-specific line endings, but the 'actual' doesn't, which is created from rendering the file. I guess it's sort of "six in one, half-dozen in the other", but should we setup "git config --global core.autocrlf true" so that Appveyor checks out with Windows line endings, which would probably be more representative of what might happen in the course of using `bb` on a Windows system?

**Comment by borkdude** [comment]
@bobisageek Why didn't we have these problems with the other tests?

**Comment by bobisageek** [comment]
In the general case, a lot of the bb tests aren't "raw" rendering files the way selmer does - the 'base' tests that run `bb` would _typically_ be using clojure print functions, which would put the system-dependent line endings into the output, but with selmer, we're often templating the exact contents of a file, which preserves whatever line ending that file happened to have.

As an example, when I run the lib tests in WSL, those same tests fail in the other direction, because my WSL console is still reading the file from the same checkout I have in Windows, which has CRLF line endings, but the `fix-line-sep` function expects whatever System/lineSeparator is. So `fix-line-sep` says that the line ending should be \n (because it think it's on linux), but the file has \r\n because it's checked out on Windows (with autocrlf setup in git).

**Comment by borkdude** [comment]
That makes sense.

**Comment by bobisageek** [comment]
Now I just have to hope that this build works so that I didn't write up that whole explanation only to be wrong. :)

**Comment by borkdude** [comment]
Yay! `{:test 845, :pass 5031, :fail 0, :error 0}`

**Pull request merged**
